#!/usr/bin/env bash
# Bash script that transfers a file from client to a server

# Check if the number of arguments is less than 4
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
file_path="$1"
ip="$2"
uname="$3"
ssh_key="$4"

# Disable strict host key checking
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$uname@$ip":~/
