#!/usr/bin/env bash
# installs nginix on the server

# sudo apt-get -y update
# sudo apt-get -y install nginx
# echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
# sudo service nginx start

# Update the package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create an HTML file with "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Ensure Nginx is listening on port 80 by configuring its default site
sudo unlink /etc/nginx/sites-enabled/default
echo 'server {
    listen 80;
    location / {
        root /var/www/html;
    }
}' | sudo tee /etc/nginx/sites-available/343103-web-01

sudo ln -s /etc/nginx/sites-available/343103-web-01 /etc/nginx/sites-enabled/

# # Test Nginx configuration
# sudo nginx -t

# Reload Nginx to apply the new configuration
sudo nginx -s reload

# # Test if Nginx returns "Hello World!" on a GET request to its root
# response=$(curl -s http://localhost)
# if [[ "$response" == *"Hello World!"* ]]; then
#     echo "Nginx is installed and configured correctly."
# else
#     echo "Nginx may not be configured correctly."
# fi
