#!/usr/bin/env bash
# Displays numbers from 1-100 and prints:
#   - FizzBuzz if number is a multiple of 3 and 5
#   - Fizz if number is a multiple of 3
#   - Buzz if number is a multiple of 5

for i in {1..100}
do
    if [ $(( i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $(( i % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $(( i % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    i=$((i + 1))
done