#!/usr/bin/env bash
# A script that displays the content of the file /etc/passwd.
# Script only displays:
#   - username
#   - user id
#   - Home directory path for the user

while IFS= read -r line
 do
  echo "$line" | cut -d ":" -f 1,3,6
done < /etc/passwd