#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8
file="/etc/hosts"
file2="hosts.new"
cp "$file" "$file2"
sed -i s/^127.*localhost/127.0.0.2\\tlocalhost/ "$file2"
echo "8.8.8.8        facebook.com" >> "$file2"
cp -f "$file2" "$file"
