#!/usr/bin/env bash
# Fix container given to run as nginx user && listen on all active IPs on port 8080
sudo sed -i "s/# user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/\b80\b/8080/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
