#!/usr/bin/env bash
# reloads Gunicorn by SIGHUP signal to its worker processes.

# Get the process ID (PID) of the Gunicorn master
MASTER_PID=$(pgrep gunicorn)

# Send a graceful reload signal to the master process
kill -s HUP "$MASTER_PID"
